### ISSUE TITLE
please, update to latest version of akka stream

### ISSUE THREAD

**Issue by matpil** [typesafehub/activator-akka-stream-java8#15]
Hi, 
is it possible to update this example with the latest version of akka.
A lot of method (as onComplete) are not yet supported.

Also BasicTransformation not compile...

Thanks and regards

--
matpil

**Comment by nikos** [comment]
+1

**Comment by nikos** [comment]
Yipiie, thanks a lot @johanandren

**Comment by johanandren** [comment]
Republishing, the updated template will appear in the activator in a few minutes
